"""Initial schema: PostGIS extension, core tables, spatial indexes.

Hand-written rather than autogenerated. Autogenerate cannot create the PostGIS
extension (it has to exist before the geography columns are valid), and it
emits noisy duplicate spatial indexes. For the first migration, writing it out
is clearer and safer.

Revision ID: 0001
Revises:
Create Date: 2026-09-02
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


POINT = geoalchemy2.Geography(
    geometry_type="POINT", srid=4326, spatial_index=False
)


def upgrade() -> None:
    # Must come first: the geography type does not exist until PostGIS is
    # installed. The postgis/postgis image ships the extension files but does
    # not necessarily enable it in every database, so do it explicitly.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "technicians",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "skills",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("shift_start", sa.Time(), nullable=False),
        sa.Column("shift_end", sa.Time(), nullable=False),
        sa.Column("home_location", POINT, nullable=False),
        sa.Column(
            "van_stock",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "max_jobs", sa.Integer(), server_default=sa.text("8"), nullable=False
        ),
        sa.CheckConstraint(
            "shift_end > shift_start", name="ck_technicians_shift_order"
        ),
        sa.CheckConstraint("max_jobs > 0", name="ck_technicians_max_jobs_positive"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "depots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("location", POINT, nullable=False),
        sa.Column(
            "stocked_parts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("customer", sa.String(length=200), nullable=False),
        sa.Column("location", POINT, nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "required_skills",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "required_parts",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("hard_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hard_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pref_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pref_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "priority", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "hard_window_end > hard_window_start", name="ck_jobs_hard_window_order"
        ),
        sa.CheckConstraint(
            "pref_window_start IS NULL "
            "OR pref_window_end IS NULL "
            "OR pref_window_end > pref_window_start",
            name="ck_jobs_pref_window_order",
        ),
        sa.CheckConstraint("duration_seconds > 0", name="ck_jobs_duration_positive"),
        sa.CheckConstraint(
            "status IN ('pending','assigned','in_progress','done','cancelled')",
            name="ck_jobs_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "solve_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column("objective_value", sa.BigInteger(), nullable=True),
        sa.Column("travel_seconds_total", sa.Integer(), nullable=True),
        sa.Column("unassigned_count", sa.Integer(), nullable=True),
        sa.Column("solver_wall_ms", sa.Integer(), nullable=True),
        sa.Column("proved_optimal", sa.Boolean(), nullable=True),
        sa.Column(
            "config_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed')",
            name="ck_solve_runs_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "assignments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("solve_run_id", sa.BigInteger(), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("technician_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence_position", sa.Integer(), nullable=False),
        sa.Column("predicted_arrival", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predicted_departure", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.CheckConstraint(
            "sequence_position >= 0", name="ck_assignments_seq_positive"
        ),
        sa.CheckConstraint(
            "predicted_departure >= predicted_arrival",
            name="ck_assignments_time_order",
        ),
        sa.ForeignKeyConstraint(
            ["solve_run_id"], ["solve_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["technician_id"], ["technicians.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("solve_run_id", "job_id", name="uq_assignments_run_job"),
        sa.UniqueConstraint(
            "solve_run_id",
            "technician_id",
            "sequence_position",
            name="uq_assignments_run_tech_seq",
        ),
    )

    # GiST indexes on the geography columns. These are what make PostGIS
    # depot-radius filtering fast; without them ST_DWithin is a full scan.
    op.create_index(
        "ix_technicians_home_location",
        "technicians",
        ["home_location"],
        postgresql_using="gist",
    )
    op.create_index(
        "ix_depots_location", "depots", ["location"], postgresql_using="gist"
    )
    op.create_index("ix_jobs_location", "jobs", ["location"], postgresql_using="gist")

    # Loading "the day" is the single hottest query in the whole system.
    op.create_index("ix_jobs_hard_window_start", "jobs", ["hard_window_start"])
    op.create_index("ix_jobs_status", "jobs", ["status"])
    op.create_index("ix_solve_runs_day", "solve_runs", ["day"])
    op.create_index("ix_assignments_solve_run_id", "assignments", ["solve_run_id"])


def downgrade() -> None:
    op.drop_index("ix_assignments_solve_run_id", table_name="assignments")
    op.drop_index("ix_solve_runs_day", table_name="solve_runs")
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_index("ix_jobs_hard_window_start", table_name="jobs")
    op.drop_index("ix_jobs_location", table_name="jobs", postgresql_using="gist")
    op.drop_index("ix_depots_location", table_name="depots", postgresql_using="gist")
    op.drop_index(
        "ix_technicians_home_location",
        table_name="technicians",
        postgresql_using="gist",
    )

    op.drop_table("assignments")
    op.drop_table("solve_runs")
    op.drop_table("jobs")
    op.drop_table("depots")
    op.drop_table("technicians")

    # The extension is deliberately NOT dropped. Other databases or schemas
    # may rely on it, and dropping it is not reversible in any useful sense.
