"""Technician access codes and bearer tokens.

Hand-written rather than autogenerated. Autogenerate would have produced the
two tables correctly, but not the partial indexes below -- and those are the
part that matters at request time.

No columns are added to `technicians`. Authentication is a relationship
between a person and a credential, not an attribute of the person, and
putting a `token` column on the row would make one device per technician a
schema-level assumption. A technician with a spare handset, or one mid-way
through replacing a broken phone, is ordinary.

Revision ID: 0003
Revises: 0002
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "technician_access_codes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("technician_id", sa.BigInteger(), nullable=False),
        # sha256 hex is exactly 64 characters. Fixed-width by construction, so
        # the length is an assertion rather than a guess at how big it gets.
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["technician_id"], ["technicians.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash", name="uq_technician_access_codes_hash"),
    )

    op.create_table(
        "technician_tokens",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("technician_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("access_code_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["technician_id"], ["technicians.id"], ondelete="CASCADE"
        ),
        # SET NULL, not CASCADE: deleting the code a token came from must not
        # silently log a technician out mid-shift. The provenance is nice to
        # have; the session is not disposable.
        sa.ForeignKeyConstraint(
            ["access_code_id"],
            ["technician_access_codes.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_technician_tokens_hash"),
    )

    # The hot path: every single /field/* request looks a token hash up and
    # filters out revoked rows. A PARTIAL index -- one that only covers rows
    # matching the WHERE clause -- is the right shape here, because revoked
    # tokens are dead weight that only grows. Postgres will use this for
    # `WHERE token_hash = ? AND revoked_at IS NULL` and the index stays the
    # size of the live set rather than the historical one.
    #
    # The unique constraint above already indexes token_hash, so this is not
    # about making the lookup possible -- it is about keeping it small.
    op.create_index(
        "ix_technician_tokens_live",
        "technician_tokens",
        ["token_hash"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    # Redemption filters on hash + unredeemed + unrevoked + unexpired. Same
    # reasoning: a redeemed code is never looked up again.
    op.create_index(
        "ix_technician_access_codes_live",
        "technician_access_codes",
        ["code_hash"],
        unique=False,
        postgresql_where=sa.text("redeemed_at IS NULL AND revoked_at IS NULL"),
    )

    # The dispatcher's access screen groups both tables by technician.
    op.create_index(
        "ix_technician_access_codes_technician",
        "technician_access_codes",
        ["technician_id"],
    )
    op.create_index(
        "ix_technician_tokens_technician",
        "technician_tokens",
        ["technician_id"],
    )


def downgrade() -> None:
    # Tokens first: it carries the FK to codes.
    op.drop_index("ix_technician_tokens_technician", table_name="technician_tokens")
    op.drop_index("ix_technician_tokens_live", table_name="technician_tokens")
    op.drop_table("technician_tokens")

    op.drop_index(
        "ix_technician_access_codes_technician",
        table_name="technician_access_codes",
    )
    op.drop_index(
        "ix_technician_access_codes_live", table_name="technician_access_codes"
    )
    op.drop_table("technician_access_codes")
