"""Append-only status events from the technician's phone.

What a technician reported, when they say it happened, and when we heard about
it. `jobs.status` becomes a derived cache of this table rather than the
primary record -- see api/field_status.py for why both exist.

Two departures from the spec's sketch, both deliberate:

* **UUID primary key, generated by the client.** This breaks the project's
  "integer primary keys so a dispatcher can say it out loud" convention, and
  should: nobody reads an event id aloud, and the client picking the key is
  what makes a retry idempotent. A phone that times out mid-request re-sends
  the SAME id and lands as ON CONFLICT DO NOTHING instead of a second event.
* **No `synced` column.** Whether the phone considers a row synced is a fact
  about the phone, and every row that reached this table is synced by
  definition. It belongs in IndexedDB, not here, where it could only ever say
  "true".

Revision ID: 0005
Revises: 0004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "job_status_events",
        # Client-generated. gen_random_uuid() is available as a server default
        # on PG13+ and deliberately NOT used: a server-side default would
        # silently paper over a client that forgot to send an id, and that
        # client would then create a duplicate on every retry.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("technician_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        # The sanitised time -- clamped into a believable band. Everything
        # downstream reads this one.
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        # What the phone actually claimed, untouched. The clamp is a
        # judgement; this is the evidence that it fired.
        sa.Column("client_occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Per-device monotonic counter, for ordering events that share a
        # second or straddle a clock change.
        sa.Column("device_seq", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["technician_id"], ["technicians.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('en_route','arrived','complete')",
            name="ck_job_status_events_status",
        ),
    )

    # The read path folds a technician's events for a day's jobs into one
    # status each, so both columns get an index.
    op.create_index("ix_job_status_events_job", "job_status_events", ["job_id"])
    op.create_index(
        "ix_job_status_events_technician", "job_status_events", ["technician_id"]
    )


def downgrade() -> None:
    # DESTRUCTIVE, and worse than 0004's was: this drops the only record of
    # what technicians reported. `jobs.status` keeps whatever the cache last
    # held, so the schedule still looks sane afterwards, which is exactly what
    # makes the loss easy to miss. There is no re-seed that brings these back.
    op.drop_index("ix_job_status_events_technician", table_name="job_status_events")
    op.drop_index("ix_job_status_events_job", table_name="job_status_events")
    op.drop_table("job_status_events")
