"""Deterministic generator for a realistic Klang Valley dispatch day.

Pure functions over plain dataclasses. Nothing here touches the database or
the network, so it is fast, importable from tests, and reusable by the phase
10 benchmark harness without standing up a stack.

Determinism is a hard requirement, not a nicety. The benchmark compares the
solver against a baseline "on the same instances"; if `--seed 42` produced a
different day on Tuesday than it did on Monday, that comparison is worthless.
Two rules keep it honest, both enforced below:

  1. All randomness comes from one `random.Random(seed)` instance, never the
     module-level `random.*` functions, which share global state with any
     other library that touches them.

  2. Never iterate a `set` when the result affects output. Python randomises
     string hashing per process (PYTHONHASHSEED), so set iteration order can
     differ between runs of the same code with the same seed. Every set is
     `sorted()` before use. JavaScript has no equivalent hazard -- JS Sets are
     insertion-ordered by specification.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from datetime import date, datetime, time, timedelta
from zoneinfo import ZoneInfo

from data.seed.catalog import (
    ARCHETYPES,
    CUSTOMER_PREFIXES,
    CUSTOMER_SUFFIXES,
    PART_CARRY_RATE,
    PART_QTY_RANGE,
    PARTS,
    SKILL_PREVALENCE,
    SKILLS,
    TECHNICIAN_NAMES,
    FAULT_DESCRIPTIONS,
    JOB_NOTES,
    JobArchetype,
    SERVICE_TYPE_LABELS,
    STREET_NAMES,
)
from data.seed.geography import (
    DEPOT_SITES,
    DISTRICT_POSTCODES,
    DISTRICTS,
    District,
    estimate_travel_seconds,
    km_to_deg,
)

# The working day. Jobs and shifts live inside this envelope.
DAY_START = time(8, 0)
DAY_END = time(18, 0)


# --- Domain objects ---------------------------------------------------------
#
# These are @dataclass, not pydantic models, and the distinction is
# deliberate. A dataclass is a plain data container: the decorator writes
# __init__, __repr__ and __eq__ from the annotated fields and does nothing
# else. In particular the type hints are NOT enforced at runtime -- passing a
# str where an int is annotated succeeds silently.
#
# That is the right trade here. This data is generated by code we control, it
# never crosses a trust boundary, and it will be constructed tens of thousands
# of times in the benchmark, where per-instance validation overhead is real.
#
# Pydantic is for the opposite situation: data arriving from outside that must
# be validated before it is believed. That is why the spec puts pydantic in
# api/models.py at the HTTP boundary and why the LLM parser in phase 13 will
# use it heavily. Same shape, different job.


@dataclass(frozen=True)
class SeedTechnician:
    ref: str
    name: str
    skills: tuple[str, ...]
    shift_start: time
    shift_end: time
    home_lat: float
    home_lon: float
    van_stock: dict[str, int] = field(default_factory=dict)
    max_jobs: int = 8
    home_district: str = ""

    @property
    def shift_seconds(self) -> int:
        s = self.shift_start.hour * 3600 + self.shift_start.minute * 60
        e = self.shift_end.hour * 3600 + self.shift_end.minute * 60
        return e - s


@dataclass(frozen=True)
class SeedDepot:
    ref: str
    name: str
    lat: float
    lon: float
    stocked_parts: dict[str, int] = field(default_factory=dict)


@dataclass(frozen=True)
class SeedJob:
    ref: str
    customer: str
    lat: float
    lon: float
    duration_seconds: int
    required_skills: tuple[str, ...]
    required_parts: tuple[str, ...]
    hard_window_start: datetime
    hard_window_end: datetime
    pref_window_start: datetime | None
    pref_window_end: datetime | None
    priority: int
    archetype: str = ""
    district: str = ""
    # --- Job detail, for the technician PWA (field phase 3) ---
    # Defaulted rather than required so every existing construction site and
    # test that builds a SeedJob keeps working untouched.
    address: str = ""
    phone: str = ""
    service_type: str = ""
    fault_description: str = ""
    note: str = ""


@dataclass(frozen=True)
class SeedInstance:
    """One generated day, complete and self-describing."""

    day: date
    timezone: str
    seed: int
    technicians: tuple[SeedTechnician, ...]
    depots: tuple[SeedDepot, ...]
    jobs: tuple[SeedJob, ...]


# --- Weighted sampling ------------------------------------------------------


def _pick_district(rng: random.Random, key: str) -> District:
    weights = [getattr(d, key) for d in DISTRICTS]
    return rng.choices(DISTRICTS, weights=weights, k=1)[0]


def _point_in(rng: random.Random, d: District) -> tuple[float, float]:
    """Sample a point around a district centre.

    Gaussian rather than uniform-in-a-circle, and clipped at 2 sigma: real
    service calls cluster hard around a district's core and thin out at the
    edges, rather than filling a disc evenly.
    """
    d_lat, d_lon = km_to_deg(d.spread_km / 2.0, d.lat)
    lat = d.lat + max(-2.0, min(2.0, rng.gauss(0, 1))) * d_lat
    lon = d.lon + max(-2.0, min(2.0, rng.gauss(0, 1))) * d_lon
    return round(lat, 6), round(lon, 6)


def _pick_archetype(rng: random.Random) -> JobArchetype:
    return rng.choices(ARCHETYPES, weights=[a.weight for a in ARCHETYPES], k=1)[0]


# --- Technicians ------------------------------------------------------------

# (start, end, relative weight). The part-time shift matters: it is the
# cheapest way to make capacity uneven, which is what gives the workload
# imbalance term in phase 6 something to actually push against.
_SHIFT_PATTERNS: tuple[tuple[time, time, float], ...] = (
    (time(8, 0), time(17, 0), 0.60),
    (time(9, 0), time(18, 0), 0.18),
    (time(8, 0), time(13, 0), 0.10),
    (time(10, 0), time(19, 0), 0.07),
    (time(7, 30), time(16, 30), 0.05),
)


def _generate_technicians(rng: random.Random, count: int) -> tuple[SeedTechnician, ...]:
    if count > len(TECHNICIAN_NAMES):
        raise ValueError(
            f"only {len(TECHNICIAN_NAMES)} technician names available, asked for {count}"
        )
    if count < 1:
        raise ValueError("need at least one technician")

    names = list(TECHNICIAN_NAMES[:count])

    # Skill coverage by construction. Every skill in the catalog is dealt to
    # at least one technician before prevalence rolls happen, so no job is
    # unassignable purely because the team cannot do it. Deliberately
    # unassignable jobs are opt-in, via generate_instance(orphan_jobs=...).
    assigned: list[set[str]] = [set() for _ in range(count)]
    for i, skill in enumerate(SKILLS):
        assigned[i % count].add(skill)

    for bucket in assigned:
        for skill in SKILLS:  # tuple, so deterministic order
            if rng.random() < SKILL_PREVALENCE[skill]:
                bucket.add(skill)

    # Part coverage, same idea: every part is carried by someone.
    stocks: list[dict[str, int]] = [{} for _ in range(count)]
    for i, part in enumerate(PARTS):
        lo, hi = PART_QTY_RANGE[part]
        stocks[i % count][part] = rng.randint(lo, hi)

    for stock in stocks:
        for part in PARTS:
            if part not in stock and rng.random() < PART_CARRY_RATE[part]:
                lo, hi = PART_QTY_RANGE[part]
                stock[part] = rng.randint(lo, hi)

    techs: list[SeedTechnician] = []
    for i in range(count):
        start, end, _ = rng.choices(
            _SHIFT_PATTERNS, weights=[p[2] for p in _SHIFT_PATTERNS], k=1
        )[0]
        district = _pick_district(rng, "home_weight")
        lat, lon = _point_in(rng, district)

        techs.append(
            SeedTechnician(
                ref=f"T{i + 1}",
                name=names[i],
                # sorted(): assigned[i] is a set, and set iteration order is
                # not stable across processes. See the module docstring.
                skills=tuple(sorted(assigned[i])),
                shift_start=start,
                shift_end=end,
                home_lat=lat,
                home_lon=lon,
                van_stock=dict(sorted(stocks[i].items())),
                max_jobs=rng.randint(6, 10),
                home_district=district.name,
            )
        )
    return tuple(techs)


# --- Jobs -------------------------------------------------------------------

# (label, start, end, relative weight). "all_day" is the loose case a
# dispatcher loves; "tight" is the SLA-driven one that does the real work of
# making the problem hard.
_WINDOW_PATTERNS: tuple[tuple[str, time, time, float], ...] = (
    ("morning", time(8, 0), time(13, 0), 0.28),
    ("afternoon", time(13, 0), time(18, 0), 0.28),
    ("all_day", time(8, 0), time(18, 0), 0.24),
    ("tight", time(0, 0), time(0, 0), 0.20),  # bounds computed per job
)


def _hard_window(
    rng: random.Random, day: date, tz: ZoneInfo, duration_s: int
) -> tuple[datetime, datetime]:
    label, start_t, end_t, _ = rng.choices(
        _WINDOW_PATTERNS, weights=[p[3] for p in _WINDOW_PATTERNS], k=1
    )[0]

    day_open = datetime.combine(day, DAY_START, tzinfo=tz)
    day_close = datetime.combine(day, DAY_END, tzinfo=tz)

    if label == "tight":
        span = rng.randint(150, 210) * 60  # 2.5 - 3.5 hours
        span = max(span, duration_s + 1800)  # never shorter than the work
        latest_start = day_close - timedelta(seconds=span)
        if latest_start <= day_open:
            return day_open, day_close
        offset = rng.randint(0, int((latest_start - day_open).total_seconds()))
        start = day_open + timedelta(seconds=offset - offset % 900)  # 15-min grid
        return start, start + timedelta(seconds=span)

    start = datetime.combine(day, start_t, tzinfo=tz)
    end = datetime.combine(day, end_t, tzinfo=tz)

    # A window shorter than the job itself is an instantly-infeasible job, and
    # an accident rather than an interesting constraint. Widen toward day end.
    if (end - start).total_seconds() < duration_s:
        end = min(day_close, start + timedelta(seconds=duration_s + 1800))
    return start, end


def _pref_window(
    rng: random.Random,
    hard_start: datetime,
    hard_end: datetime,
    duration_s: int,
) -> tuple[datetime | None, datetime | None]:
    """A narrower promise inside the SLA window, for ~60% of jobs.

    Missing this is legal but penalised. Jobs without one contribute nothing
    to the lateness term.
    """
    if rng.random() > 0.60:
        return None, None

    span = 2 * 3600
    slack = (hard_end - hard_start).total_seconds() - max(span, duration_s)
    if slack <= 0:
        return hard_start, hard_end

    offset = rng.randint(0, int(slack))
    start = hard_start + timedelta(seconds=offset - offset % 900)
    end = min(hard_end, start + timedelta(seconds=span))
    return start, end


def _customer_name(rng: random.Random, district: District) -> str:
    prefix = rng.choice(CUSTOMER_PREFIXES)
    suffix = rng.choice(CUSTOMER_SUFFIXES)
    # Some names carry the district, the way real building names do.
    if rng.random() < 0.30:
        return f"{prefix} {district.name}"
    return f"{prefix} {suffix}"


def _address(rng: random.Random, district: District) -> str:
    """A structurally Malaysian address: "12, Jalan Setiabakti 3, 59100 Bangsar".

    Synthetic, and not reverse-geocoded from the job's actual coordinates --
    the point is a realistic *shape and length* for the detail screen to lay
    out, not a real place. Navigation uses the coordinates, which are real
    enough to route between; the address is what a human reads.
    """
    lot = rng.randint(1, 240)
    street = rng.choice(STREET_NAMES)
    # Roughly half of KL streets carry a number suffix -- Jalan Telawi 3.
    suffix = f" {rng.randint(1, 9)}" if rng.random() < 0.5 else ""
    postcode = DISTRICT_POSTCODES.get(district.name, "50000")
    return f"{lot}, Jalan {street}{suffix}, {postcode} {district.name}"


def _phone(rng: random.Random) -> str:
    """E.164. Half landlines (+603), half mobiles (+601x).

    Stored in international form because the detail screen turns it into a
    `tel:` link, and a local-format number with a leading 0 does not dial
    reliably from a phone that thinks it is somewhere else.
    """
    if rng.random() < 0.5:
        return f"+603{rng.randint(10000000, 99999999)}"
    return f"+601{rng.randint(0, 9)}{rng.randint(1000000, 9999999)}"


def _generate_jobs(
    rng: random.Random,
    count: int,
    day: date,
    tz: ZoneInfo,
    orphan_jobs: int,
) -> tuple[SeedJob, ...]:
    jobs: list[SeedJob] = []

    for i in range(count):
        arch = _pick_archetype(rng)
        district = _pick_district(rng, "job_weight")
        lat, lon = _point_in(rng, district)

        lo, hi = arch.duration_range
        # Round to 5 minutes. Real job estimates are never 47 minutes.
        duration_s = (rng.randint(lo, hi) // 5) * 5 * 60

        parts = list(arch.parts)
        for part, prob in arch.maybe_parts:
            if rng.random() < prob:
                parts.append(part)

        hard_start, hard_end = _hard_window(rng, day, tz, duration_s)
        pref_start, pref_end = _pref_window(rng, hard_start, hard_end, duration_s)

        # 1 = HIGHEST, 2 = normal, 3 = lowest. Written this way round so a
        # dispatcher saying "make it top priority" means 1 everywhere -- in
        # the prompt, the schema, the API and the seeded data. A higher
        # urgency_bias therefore pushes the number DOWN.
        roll = rng.random() + arch.urgency_bias * 0.35
        priority = 1 if roll > 0.92 else (2 if roll > 0.68 else 3)

        jobs.append(
            SeedJob(
                ref=f"J{i + 1}",
                customer=_customer_name(rng, district),
                lat=lat,
                lon=lon,
                duration_seconds=duration_s,
                required_skills=tuple(sorted(set(arch.skills))),
                required_parts=tuple(sorted(set(parts))),
                hard_window_start=hard_start,
                hard_window_end=hard_end,
                pref_window_start=pref_start,
                pref_window_end=pref_end,
                priority=priority,
                archetype=arch.name,
                district=district.name,
                address=_address(rng, district),
                phone=_phone(rng),
                service_type=SERVICE_TYPE_LABELS.get(arch.name, arch.name),
                fault_description=rng.choice(FAULT_DESCRIPTIONS[arch.name]),
                # Sparse on purpose. Most jobs have no note, and the detail
                # screen has to look right without one -- generating a note
                # for every job would hide that.
                note=rng.choice(JOB_NOTES) if rng.random() < 0.25 else "",
            )
        )

    # Opt-in unassignable jobs: they require a skill no technician holds.
    # Default zero. These exist so phase 7's explainer has something
    # unambiguous to explain, and so the phase 5 checker can be tested against
    # a case where leaving a job out is the only correct answer.
    for k in range(orphan_jobs):
        base = jobs[k % len(jobs)] if jobs else None
        district = _pick_district(rng, "job_weight")
        lat, lon = _point_in(rng, district)
        jobs.append(
            SeedJob(
                ref=f"J{count + k + 1}",
                customer=f"{_customer_name(rng, district)} (orphan)",
                lat=lat,
                lon=lon,
                duration_seconds=base.duration_seconds if base else 3600,
                required_skills=("cryogenic_certified",),  # nobody has this
                required_parts=(),
                hard_window_start=datetime.combine(day, DAY_START, tzinfo=tz),
                hard_window_end=datetime.combine(day, DAY_END, tzinfo=tz),
                pref_window_start=None,
                pref_window_end=None,
                priority=1,
                archetype="orphan",
                district=district.name,
                address=_address(rng, district),
                phone=_phone(rng),
                service_type=SERVICE_TYPE_LABELS["orphan"],
                fault_description=FAULT_DESCRIPTIONS["orphan"][0],
            )
        )

    return tuple(jobs)


def _generate_depots(rng: random.Random) -> tuple[SeedDepot, ...]:
    depots = []
    for i, (name, lat, lon) in enumerate(DEPOT_SITES):
        # Depots hold everything, in bulk.
        stock = {p: rng.randint(10, 40) for p in PARTS}
        depots.append(
            SeedDepot(
                ref=f"D{i + 1}",
                name=name,
                lat=lat,
                lon=lon,
                stocked_parts=stock,
            )
        )
    return tuple(depots)


# --- Entry point ------------------------------------------------------------


def generate_instance(
    *,
    n_jobs: int = 40,
    n_technicians: int = 8,
    day: date | None = None,
    seed: int = 42,
    timezone: str = "Asia/Kuala_Lumpur",
    orphan_jobs: int = 0,
) -> SeedInstance:
    """Build one day. Same arguments always produce the same instance.

    Keyword-only (note the bare `*` in the signature): callers must write
    `generate_instance(n_jobs=40, n_technicians=8)`. With two adjacent ints
    that are easy to transpose, forcing the names at every call site is worth
    the keystrokes. Python has no positional-argument equivalent in JS.
    """
    if n_jobs < 1:
        raise ValueError("need at least one job")

    tz = ZoneInfo(timezone)
    rng = random.Random(seed)
    target_day = day or date.today()

    # Order matters for determinism: technicians, then depots, then jobs.
    # Changing this order changes every generated instance for a given seed.
    technicians = _generate_technicians(rng, n_technicians)
    depots = _generate_depots(rng)
    jobs = _generate_jobs(rng, n_jobs, target_day, tz, orphan_jobs)

    return SeedInstance(
        day=target_day,
        timezone=timezone,
        seed=seed,
        technicians=technicians,
        depots=depots,
        jobs=jobs,
    )


# --- Sanity checks on the generated data ------------------------------------
#
# This is NOT the phase 5 feasibility checker. That one validates a *schedule*
# against the constraints. This validates the *input* -- it catches a
# generator that has quietly produced an impossible or trivial day, so that
# when the solver misbehaves later you can rule out the data first.


def validate_instance(inst: SeedInstance) -> list[str]:
    """Return a list of problems. Empty list means the instance looks sane."""
    problems: list[str] = []

    team_skills = sorted({s for t in inst.technicians for s in t.skills})
    van_parts = sorted({p for t in inst.technicians for p in t.van_stock})

    for job in inst.jobs:
        window_s = (job.hard_window_end - job.hard_window_start).total_seconds()
        if window_s < job.duration_seconds:
            problems.append(
                f"{job.ref}: hard window {int(window_s / 60)}min is shorter than "
                f"its {int(job.duration_seconds / 60)}min duration"
            )

        if job.pref_window_start and job.pref_window_end:
            if (
                job.pref_window_start < job.hard_window_start
                or job.pref_window_end > job.hard_window_end
            ):
                problems.append(f"{job.ref}: preferred window escapes the hard window")

        missing_skills = [s for s in job.required_skills if s not in team_skills]
        if missing_skills and job.archetype != "orphan":
            problems.append(
                f"{job.ref}: needs skill(s) {missing_skills} that no technician holds"
            )

        missing_parts = [p for p in job.required_parts if p not in van_parts]
        if missing_parts:
            problems.append(
                f"{job.ref}: needs part(s) {missing_parts} that no van carries"
            )

        # A job whose window cannot overlap anyone's shift is dead on arrival.
        reachable = any(
            _overlaps(job, t, inst.timezone) for t in inst.technicians
        )
        if not reachable and job.archetype != "orphan":
            problems.append(f"{job.ref}: hard window overlaps no technician's shift")

    return problems


def _overlaps(job: SeedJob, tech: SeedTechnician, timezone: str) -> bool:
    tz = ZoneInfo(timezone)
    day = job.hard_window_start.date()
    shift_start = datetime.combine(day, tech.shift_start, tzinfo=tz)
    shift_end = datetime.combine(day, tech.shift_end, tzinfo=tz)
    latest_start = min(job.hard_window_end, shift_end) - timedelta(
        seconds=job.duration_seconds
    )
    return latest_start >= max(job.hard_window_start, shift_start)


def load_ratio(inst: SeedInstance) -> float:
    """Work required divided by technician capacity available.

    Above ~0.85 expect unassigned jobs, and that is the intended behaviour --
    the spec is explicit that infeasibility is the normal case. Below ~0.5 the
    instance is too easy to say anything interesting about the solver.

    Travel is estimated with the haversine helper, so this figure is
    indicative only. It is a smell test for the generator, never a reported
    result.
    """
    work_s = sum(j.duration_seconds for j in inst.jobs)

    # Mean pairwise travel over a bounded sample, as a stand-in for the travel
    # each job drags along with it.
    sample = inst.jobs[:24]
    pairs = [
        estimate_travel_seconds(a.lat, a.lon, b.lat, b.lon)
        for i, a in enumerate(sample)
        for b in sample[i + 1 :]
    ]
    mean_travel = (sum(pairs) / len(pairs)) if pairs else 0
    # Consecutive jobs on a sensible route are far closer than two random
    # jobs, so discount the mean heavily.
    travel_s = mean_travel * 0.45 * len(inst.jobs)

    capacity_s = sum(t.shift_seconds for t in inst.technicians)
    return (work_s + travel_s) / capacity_s if capacity_s else float("inf")


async def snap_instance(inst: SeedInstance, osrm_url: str) -> tuple[SeedInstance, object]:
    """Return the instance with every coordinate moved onto the road network.

    Applied to technicians, jobs and depots alike -- a technician home in the
    middle of a housing estate's green space produces exactly the same wrong
    first leg as a job does.

    Returns the instance unchanged if OSRM is unreachable; `snap_coords`
    reports what it managed, and the caller decides whether that is good
    enough. Seeding must not become impossible because the routing container
    is down.
    """
    import dataclasses

    from routing.base import Coord
    from routing.snap import snap_coords

    techs, jobs, depots = inst.technicians, inst.jobs, inst.depots
    coords = (
        [Coord(t.home_lat, t.home_lon) for t in techs]
        + [Coord(j.lat, j.lon) for j in jobs]
        + [Coord(d.lat, d.lon) for d in depots]
    )
    snapped, report = await snap_coords(coords, osrm_url)

    nt, nj = len(techs), len(jobs)
    new_techs = tuple(
        dataclasses.replace(t, home_lat=c.lat, home_lon=c.lon)
        for t, c in zip(techs, snapped[:nt])
    )
    new_jobs = tuple(
        dataclasses.replace(j, lat=c.lat, lon=c.lon)
        for j, c in zip(jobs, snapped[nt:nt + nj])
    )
    new_depots = tuple(
        dataclasses.replace(d, lat=c.lat, lon=c.lon)
        for d, c in zip(depots, snapped[nt + nj:])
    )
    return (
        dataclasses.replace(
            inst, technicians=new_techs, jobs=new_jobs, depots=new_depots
        ),
        report,
    )
